apiVersion: v2
appVersion: latest
description: A Helm chart for Kubernetes
name: ungate
type: application
version: 0.1.0
maintainers:
  - name: xom4ek
    email: aleksei.lazarev@p2p.org
icon: https://avatars.githubusercontent.com/u/143101892?s=200&v=4
